class TradingClient():
    def __init__():
        ...
    
    def connectToGateIo():
        ...
    
    def placeOrder():
        ...

    def checkOpenOrders():
        ...

    def cancelOrder():
        ...